/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ZoclawRouteImport } from './routes/zoclaw'
import { Route as TeamRouteImport } from './routes/team'
import { Route as ShowcaseRouteImport } from './routes/showcase'
import { Route as ScriptsRouteImport } from './routes/scripts'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as ModelsRouteImport } from './routes/models'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HomeRouteImport } from './routes/home'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as CharactersRouteImport } from './routes/characters'
import { Route as BasesRouteImport } from './routes/bases'
import { Route as AssetsRouteImport } from './routes/assets'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TeamIndexRouteImport } from './routes/team.index'
import { Route as ScriptsIndexRouteImport } from './routes/scripts.index'
import { Route as CommunityIndexRouteImport } from './routes/community.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AccountIndexRouteImport } from './routes/account.index'
import { Route as WorkspaceWorkspaceIdRouteImport } from './routes/workspace.$workspaceId'
import { Route as TeamUsageRouteImport } from './routes/team.usage'
import { Route as TeamMembersRouteImport } from './routes/team.members'
import { Route as TeamLogsRouteImport } from './routes/team.logs'
import { Route as TeamApprovalsRouteImport } from './routes/team.approvals'
import { Route as ShowcaseItemIdRouteImport } from './routes/showcase.$itemId'
import { Route as ScriptsScriptIdRouteImport } from './routes/scripts.$scriptId'
import { Route as ProjectsProjectIdRouteImport } from './routes/projects.$projectId'
import { Route as CommunityPostIdRouteImport } from './routes/community.$postId'
import { Route as CharactersRelationsRouteImport } from './routes/characters.relations'
import { Route as CharactersCharacterIdRouteImport } from './routes/characters.$characterId'
import { Route as AdminTenantsRouteImport } from './routes/admin.tenants'
import { Route as AdminModelsRouteImport } from './routes/admin.models'
import { Route as AdminBillingRouteImport } from './routes/admin.billing'
import { Route as AccountSubscriptionRouteImport } from './routes/account.subscription'
import { Route as AccountSecurityRouteImport } from './routes/account.security'
import { Route as AccountRewardsRouteImport } from './routes/account.rewards'
import { Route as AccountPostsRouteImport } from './routes/account.posts'
import { Route as AccountNotificationsRouteImport } from './routes/account.notifications'
import { Route as AccountAssetsRouteImport } from './routes/account.assets'
import { Route as AssetsTabIdRouteImport } from './routes/assets_.$tab.$id'
import { Route as ApiPublicTestAitokenvibeRouteImport } from './routes/api/public/test-aitokenvibe'

const ZoclawRoute = ZoclawRouteImport.update({
  id: '/zoclaw',
  path: '/zoclaw',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowcaseRoute = ShowcaseRouteImport.update({
  id: '/showcase',
  path: '/showcase',
  getParentRoute: () => rootRouteImport,
} as any)
const ScriptsRoute = ScriptsRouteImport.update({
  id: '/scripts',
  path: '/scripts',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelsRoute = ModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const CharactersRoute = CharactersRouteImport.update({
  id: '/characters',
  path: '/characters',
  getParentRoute: () => rootRouteImport,
} as any)
const BasesRoute = BasesRouteImport.update({
  id: '/bases',
  path: '/bases',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetsRoute = AssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamIndexRoute = TeamIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TeamRoute,
} as any)
const ScriptsIndexRoute = ScriptsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ScriptsRoute,
} as any)
const CommunityIndexRoute = CommunityIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CommunityRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccountRoute,
} as any)
const WorkspaceWorkspaceIdRoute = WorkspaceWorkspaceIdRouteImport.update({
  id: '/workspace/$workspaceId',
  path: '/workspace/$workspaceId',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamUsageRoute = TeamUsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => TeamRoute,
} as any)
const TeamMembersRoute = TeamMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => TeamRoute,
} as any)
const TeamLogsRoute = TeamLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => TeamRoute,
} as any)
const TeamApprovalsRoute = TeamApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => TeamRoute,
} as any)
const ShowcaseItemIdRoute = ShowcaseItemIdRouteImport.update({
  id: '/$itemId',
  path: '/$itemId',
  getParentRoute: () => ShowcaseRoute,
} as any)
const ScriptsScriptIdRoute = ScriptsScriptIdRouteImport.update({
  id: '/$scriptId',
  path: '/$scriptId',
  getParentRoute: () => ScriptsRoute,
} as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: '/$projectId',
  path: '/$projectId',
  getParentRoute: () => ProjectsRoute,
} as any)
const CommunityPostIdRoute = CommunityPostIdRouteImport.update({
  id: '/$postId',
  path: '/$postId',
  getParentRoute: () => CommunityRoute,
} as any)
const CharactersRelationsRoute = CharactersRelationsRouteImport.update({
  id: '/relations',
  path: '/relations',
  getParentRoute: () => CharactersRoute,
} as any)
const CharactersCharacterIdRoute = CharactersCharacterIdRouteImport.update({
  id: '/$characterId',
  path: '/$characterId',
  getParentRoute: () => CharactersRoute,
} as any)
const AdminTenantsRoute = AdminTenantsRouteImport.update({
  id: '/tenants',
  path: '/tenants',
  getParentRoute: () => AdminRoute,
} as any)
const AdminModelsRoute = AdminModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBillingRoute = AdminBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AdminRoute,
} as any)
const AccountSubscriptionRoute = AccountSubscriptionRouteImport.update({
  id: '/subscription',
  path: '/subscription',
  getParentRoute: () => AccountRoute,
} as any)
const AccountSecurityRoute = AccountSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AccountRoute,
} as any)
const AccountRewardsRoute = AccountRewardsRouteImport.update({
  id: '/rewards',
  path: '/rewards',
  getParentRoute: () => AccountRoute,
} as any)
const AccountPostsRoute = AccountPostsRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => AccountRoute,
} as any)
const AccountNotificationsRoute = AccountNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AccountRoute,
} as any)
const AccountAssetsRoute = AccountAssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => AccountRoute,
} as any)
const AssetsTabIdRoute = AssetsTabIdRouteImport.update({
  id: '/assets_/$tab/$id',
  path: '/assets/$tab/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTestAitokenvibeRoute =
  ApiPublicTestAitokenvibeRouteImport.update({
    id: '/api/public/test-aitokenvibe',
    path: '/api/public/test-aitokenvibe',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/assets': typeof AssetsRoute
  '/bases': typeof BasesRoute
  '/characters': typeof CharactersRouteWithChildren
  '/community': typeof CommunityRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/models': typeof ModelsRoute
  '/pricing': typeof PricingRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/scripts': typeof ScriptsRouteWithChildren
  '/showcase': typeof ShowcaseRouteWithChildren
  '/team': typeof TeamRouteWithChildren
  '/zoclaw': typeof ZoclawRoute
  '/account/assets': typeof AccountAssetsRoute
  '/account/notifications': typeof AccountNotificationsRoute
  '/account/posts': typeof AccountPostsRoute
  '/account/rewards': typeof AccountRewardsRoute
  '/account/security': typeof AccountSecurityRoute
  '/account/subscription': typeof AccountSubscriptionRoute
  '/admin/billing': typeof AdminBillingRoute
  '/admin/models': typeof AdminModelsRoute
  '/admin/tenants': typeof AdminTenantsRoute
  '/characters/$characterId': typeof CharactersCharacterIdRoute
  '/characters/relations': typeof CharactersRelationsRoute
  '/community/$postId': typeof CommunityPostIdRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/scripts/$scriptId': typeof ScriptsScriptIdRoute
  '/showcase/$itemId': typeof ShowcaseItemIdRoute
  '/team/approvals': typeof TeamApprovalsRoute
  '/team/logs': typeof TeamLogsRoute
  '/team/members': typeof TeamMembersRoute
  '/team/usage': typeof TeamUsageRoute
  '/workspace/$workspaceId': typeof WorkspaceWorkspaceIdRoute
  '/account/': typeof AccountIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/community/': typeof CommunityIndexRoute
  '/scripts/': typeof ScriptsIndexRoute
  '/team/': typeof TeamIndexRoute
  '/api/public/test-aitokenvibe': typeof ApiPublicTestAitokenvibeRoute
  '/assets/$tab/$id': typeof AssetsTabIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assets': typeof AssetsRoute
  '/bases': typeof BasesRoute
  '/characters': typeof CharactersRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/models': typeof ModelsRoute
  '/pricing': typeof PricingRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/showcase': typeof ShowcaseRouteWithChildren
  '/zoclaw': typeof ZoclawRoute
  '/account/assets': typeof AccountAssetsRoute
  '/account/notifications': typeof AccountNotificationsRoute
  '/account/posts': typeof AccountPostsRoute
  '/account/rewards': typeof AccountRewardsRoute
  '/account/security': typeof AccountSecurityRoute
  '/account/subscription': typeof AccountSubscriptionRoute
  '/admin/billing': typeof AdminBillingRoute
  '/admin/models': typeof AdminModelsRoute
  '/admin/tenants': typeof AdminTenantsRoute
  '/characters/$characterId': typeof CharactersCharacterIdRoute
  '/characters/relations': typeof CharactersRelationsRoute
  '/community/$postId': typeof CommunityPostIdRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/scripts/$scriptId': typeof ScriptsScriptIdRoute
  '/showcase/$itemId': typeof ShowcaseItemIdRoute
  '/team/approvals': typeof TeamApprovalsRoute
  '/team/logs': typeof TeamLogsRoute
  '/team/members': typeof TeamMembersRoute
  '/team/usage': typeof TeamUsageRoute
  '/workspace/$workspaceId': typeof WorkspaceWorkspaceIdRoute
  '/account': typeof AccountIndexRoute
  '/admin': typeof AdminIndexRoute
  '/community': typeof CommunityIndexRoute
  '/scripts': typeof ScriptsIndexRoute
  '/team': typeof TeamIndexRoute
  '/api/public/test-aitokenvibe': typeof ApiPublicTestAitokenvibeRoute
  '/assets/$tab/$id': typeof AssetsTabIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/assets': typeof AssetsRoute
  '/bases': typeof BasesRoute
  '/characters': typeof CharactersRouteWithChildren
  '/community': typeof CommunityRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/models': typeof ModelsRoute
  '/pricing': typeof PricingRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/scripts': typeof ScriptsRouteWithChildren
  '/showcase': typeof ShowcaseRouteWithChildren
  '/team': typeof TeamRouteWithChildren
  '/zoclaw': typeof ZoclawRoute
  '/account/assets': typeof AccountAssetsRoute
  '/account/notifications': typeof AccountNotificationsRoute
  '/account/posts': typeof AccountPostsRoute
  '/account/rewards': typeof AccountRewardsRoute
  '/account/security': typeof AccountSecurityRoute
  '/account/subscription': typeof AccountSubscriptionRoute
  '/admin/billing': typeof AdminBillingRoute
  '/admin/models': typeof AdminModelsRoute
  '/admin/tenants': typeof AdminTenantsRoute
  '/characters/$characterId': typeof CharactersCharacterIdRoute
  '/characters/relations': typeof CharactersRelationsRoute
  '/community/$postId': typeof CommunityPostIdRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/scripts/$scriptId': typeof ScriptsScriptIdRoute
  '/showcase/$itemId': typeof ShowcaseItemIdRoute
  '/team/approvals': typeof TeamApprovalsRoute
  '/team/logs': typeof TeamLogsRoute
  '/team/members': typeof TeamMembersRoute
  '/team/usage': typeof TeamUsageRoute
  '/workspace/$workspaceId': typeof WorkspaceWorkspaceIdRoute
  '/account/': typeof AccountIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/community/': typeof CommunityIndexRoute
  '/scripts/': typeof ScriptsIndexRoute
  '/team/': typeof TeamIndexRoute
  '/api/public/test-aitokenvibe': typeof ApiPublicTestAitokenvibeRoute
  '/assets_/$tab/$id': typeof AssetsTabIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/admin'
    | '/assets'
    | '/bases'
    | '/characters'
    | '/community'
    | '/forgot-password'
    | '/home'
    | '/login'
    | '/models'
    | '/pricing'
    | '/projects'
    | '/register'
    | '/reset-password'
    | '/scripts'
    | '/showcase'
    | '/team'
    | '/zoclaw'
    | '/account/assets'
    | '/account/notifications'
    | '/account/posts'
    | '/account/rewards'
    | '/account/security'
    | '/account/subscription'
    | '/admin/billing'
    | '/admin/models'
    | '/admin/tenants'
    | '/characters/$characterId'
    | '/characters/relations'
    | '/community/$postId'
    | '/projects/$projectId'
    | '/scripts/$scriptId'
    | '/showcase/$itemId'
    | '/team/approvals'
    | '/team/logs'
    | '/team/members'
    | '/team/usage'
    | '/workspace/$workspaceId'
    | '/account/'
    | '/admin/'
    | '/community/'
    | '/scripts/'
    | '/team/'
    | '/api/public/test-aitokenvibe'
    | '/assets/$tab/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assets'
    | '/bases'
    | '/characters'
    | '/forgot-password'
    | '/home'
    | '/login'
    | '/models'
    | '/pricing'
    | '/projects'
    | '/register'
    | '/reset-password'
    | '/showcase'
    | '/zoclaw'
    | '/account/assets'
    | '/account/notifications'
    | '/account/posts'
    | '/account/rewards'
    | '/account/security'
    | '/account/subscription'
    | '/admin/billing'
    | '/admin/models'
    | '/admin/tenants'
    | '/characters/$characterId'
    | '/characters/relations'
    | '/community/$postId'
    | '/projects/$projectId'
    | '/scripts/$scriptId'
    | '/showcase/$itemId'
    | '/team/approvals'
    | '/team/logs'
    | '/team/members'
    | '/team/usage'
    | '/workspace/$workspaceId'
    | '/account'
    | '/admin'
    | '/community'
    | '/scripts'
    | '/team'
    | '/api/public/test-aitokenvibe'
    | '/assets/$tab/$id'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/admin'
    | '/assets'
    | '/bases'
    | '/characters'
    | '/community'
    | '/forgot-password'
    | '/home'
    | '/login'
    | '/models'
    | '/pricing'
    | '/projects'
    | '/register'
    | '/reset-password'
    | '/scripts'
    | '/showcase'
    | '/team'
    | '/zoclaw'
    | '/account/assets'
    | '/account/notifications'
    | '/account/posts'
    | '/account/rewards'
    | '/account/security'
    | '/account/subscription'
    | '/admin/billing'
    | '/admin/models'
    | '/admin/tenants'
    | '/characters/$characterId'
    | '/characters/relations'
    | '/community/$postId'
    | '/projects/$projectId'
    | '/scripts/$scriptId'
    | '/showcase/$itemId'
    | '/team/approvals'
    | '/team/logs'
    | '/team/members'
    | '/team/usage'
    | '/workspace/$workspaceId'
    | '/account/'
    | '/admin/'
    | '/community/'
    | '/scripts/'
    | '/team/'
    | '/api/public/test-aitokenvibe'
    | '/assets_/$tab/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  AssetsRoute: typeof AssetsRoute
  BasesRoute: typeof BasesRoute
  CharactersRoute: typeof CharactersRouteWithChildren
  CommunityRoute: typeof CommunityRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HomeRoute: typeof HomeRoute
  LoginRoute: typeof LoginRoute
  ModelsRoute: typeof ModelsRoute
  PricingRoute: typeof PricingRoute
  ProjectsRoute: typeof ProjectsRouteWithChildren
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ScriptsRoute: typeof ScriptsRouteWithChildren
  ShowcaseRoute: typeof ShowcaseRouteWithChildren
  TeamRoute: typeof TeamRouteWithChildren
  ZoclawRoute: typeof ZoclawRoute
  WorkspaceWorkspaceIdRoute: typeof WorkspaceWorkspaceIdRoute
  ApiPublicTestAitokenvibeRoute: typeof ApiPublicTestAitokenvibeRoute
  AssetsTabIdRoute: typeof AssetsTabIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/zoclaw': {
      id: '/zoclaw'
      path: '/zoclaw'
      fullPath: '/zoclaw'
      preLoaderRoute: typeof ZoclawRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/showcase': {
      id: '/showcase'
      path: '/showcase'
      fullPath: '/showcase'
      preLoaderRoute: typeof ShowcaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scripts': {
      id: '/scripts'
      path: '/scripts'
      fullPath: '/scripts'
      preLoaderRoute: typeof ScriptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models': {
      id: '/models'
      path: '/models'
      fullPath: '/models'
      preLoaderRoute: typeof ModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/characters': {
      id: '/characters'
      path: '/characters'
      fullPath: '/characters'
      preLoaderRoute: typeof CharactersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bases': {
      id: '/bases'
      path: '/bases'
      fullPath: '/bases'
      preLoaderRoute: typeof BasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assets': {
      id: '/assets'
      path: '/assets'
      fullPath: '/assets'
      preLoaderRoute: typeof AssetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team/': {
      id: '/team/'
      path: '/'
      fullPath: '/team/'
      preLoaderRoute: typeof TeamIndexRouteImport
      parentRoute: typeof TeamRoute
    }
    '/scripts/': {
      id: '/scripts/'
      path: '/'
      fullPath: '/scripts/'
      preLoaderRoute: typeof ScriptsIndexRouteImport
      parentRoute: typeof ScriptsRoute
    }
    '/community/': {
      id: '/community/'
      path: '/'
      fullPath: '/community/'
      preLoaderRoute: typeof CommunityIndexRouteImport
      parentRoute: typeof CommunityRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/account/': {
      id: '/account/'
      path: '/'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof AccountRoute
    }
    '/workspace/$workspaceId': {
      id: '/workspace/$workspaceId'
      path: '/workspace/$workspaceId'
      fullPath: '/workspace/$workspaceId'
      preLoaderRoute: typeof WorkspaceWorkspaceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team/usage': {
      id: '/team/usage'
      path: '/usage'
      fullPath: '/team/usage'
      preLoaderRoute: typeof TeamUsageRouteImport
      parentRoute: typeof TeamRoute
    }
    '/team/members': {
      id: '/team/members'
      path: '/members'
      fullPath: '/team/members'
      preLoaderRoute: typeof TeamMembersRouteImport
      parentRoute: typeof TeamRoute
    }
    '/team/logs': {
      id: '/team/logs'
      path: '/logs'
      fullPath: '/team/logs'
      preLoaderRoute: typeof TeamLogsRouteImport
      parentRoute: typeof TeamRoute
    }
    '/team/approvals': {
      id: '/team/approvals'
      path: '/approvals'
      fullPath: '/team/approvals'
      preLoaderRoute: typeof TeamApprovalsRouteImport
      parentRoute: typeof TeamRoute
    }
    '/showcase/$itemId': {
      id: '/showcase/$itemId'
      path: '/$itemId'
      fullPath: '/showcase/$itemId'
      preLoaderRoute: typeof ShowcaseItemIdRouteImport
      parentRoute: typeof ShowcaseRoute
    }
    '/scripts/$scriptId': {
      id: '/scripts/$scriptId'
      path: '/$scriptId'
      fullPath: '/scripts/$scriptId'
      preLoaderRoute: typeof ScriptsScriptIdRouteImport
      parentRoute: typeof ScriptsRoute
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/community/$postId': {
      id: '/community/$postId'
      path: '/$postId'
      fullPath: '/community/$postId'
      preLoaderRoute: typeof CommunityPostIdRouteImport
      parentRoute: typeof CommunityRoute
    }
    '/characters/relations': {
      id: '/characters/relations'
      path: '/relations'
      fullPath: '/characters/relations'
      preLoaderRoute: typeof CharactersRelationsRouteImport
      parentRoute: typeof CharactersRoute
    }
    '/characters/$characterId': {
      id: '/characters/$characterId'
      path: '/$characterId'
      fullPath: '/characters/$characterId'
      preLoaderRoute: typeof CharactersCharacterIdRouteImport
      parentRoute: typeof CharactersRoute
    }
    '/admin/tenants': {
      id: '/admin/tenants'
      path: '/tenants'
      fullPath: '/admin/tenants'
      preLoaderRoute: typeof AdminTenantsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/models': {
      id: '/admin/models'
      path: '/models'
      fullPath: '/admin/models'
      preLoaderRoute: typeof AdminModelsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/billing': {
      id: '/admin/billing'
      path: '/billing'
      fullPath: '/admin/billing'
      preLoaderRoute: typeof AdminBillingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/account/subscription': {
      id: '/account/subscription'
      path: '/subscription'
      fullPath: '/account/subscription'
      preLoaderRoute: typeof AccountSubscriptionRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/security': {
      id: '/account/security'
      path: '/security'
      fullPath: '/account/security'
      preLoaderRoute: typeof AccountSecurityRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/rewards': {
      id: '/account/rewards'
      path: '/rewards'
      fullPath: '/account/rewards'
      preLoaderRoute: typeof AccountRewardsRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/posts': {
      id: '/account/posts'
      path: '/posts'
      fullPath: '/account/posts'
      preLoaderRoute: typeof AccountPostsRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/notifications': {
      id: '/account/notifications'
      path: '/notifications'
      fullPath: '/account/notifications'
      preLoaderRoute: typeof AccountNotificationsRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/assets': {
      id: '/account/assets'
      path: '/assets'
      fullPath: '/account/assets'
      preLoaderRoute: typeof AccountAssetsRouteImport
      parentRoute: typeof AccountRoute
    }
    '/assets_/$tab/$id': {
      id: '/assets_/$tab/$id'
      path: '/assets/$tab/$id'
      fullPath: '/assets/$tab/$id'
      preLoaderRoute: typeof AssetsTabIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/test-aitokenvibe': {
      id: '/api/public/test-aitokenvibe'
      path: '/api/public/test-aitokenvibe'
      fullPath: '/api/public/test-aitokenvibe'
      preLoaderRoute: typeof ApiPublicTestAitokenvibeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AccountRouteChildren {
  AccountAssetsRoute: typeof AccountAssetsRoute
  AccountNotificationsRoute: typeof AccountNotificationsRoute
  AccountPostsRoute: typeof AccountPostsRoute
  AccountRewardsRoute: typeof AccountRewardsRoute
  AccountSecurityRoute: typeof AccountSecurityRoute
  AccountSubscriptionRoute: typeof AccountSubscriptionRoute
  AccountIndexRoute: typeof AccountIndexRoute
}

const AccountRouteChildren: AccountRouteChildren = {
  AccountAssetsRoute: AccountAssetsRoute,
  AccountNotificationsRoute: AccountNotificationsRoute,
  AccountPostsRoute: AccountPostsRoute,
  AccountRewardsRoute: AccountRewardsRoute,
  AccountSecurityRoute: AccountSecurityRoute,
  AccountSubscriptionRoute: AccountSubscriptionRoute,
  AccountIndexRoute: AccountIndexRoute,
}

const AccountRouteWithChildren =
  AccountRoute._addFileChildren(AccountRouteChildren)

interface AdminRouteChildren {
  AdminBillingRoute: typeof AdminBillingRoute
  AdminModelsRoute: typeof AdminModelsRoute
  AdminTenantsRoute: typeof AdminTenantsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBillingRoute: AdminBillingRoute,
  AdminModelsRoute: AdminModelsRoute,
  AdminTenantsRoute: AdminTenantsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface CharactersRouteChildren {
  CharactersCharacterIdRoute: typeof CharactersCharacterIdRoute
  CharactersRelationsRoute: typeof CharactersRelationsRoute
}

const CharactersRouteChildren: CharactersRouteChildren = {
  CharactersCharacterIdRoute: CharactersCharacterIdRoute,
  CharactersRelationsRoute: CharactersRelationsRoute,
}

const CharactersRouteWithChildren = CharactersRoute._addFileChildren(
  CharactersRouteChildren,
)

interface CommunityRouteChildren {
  CommunityPostIdRoute: typeof CommunityPostIdRoute
  CommunityIndexRoute: typeof CommunityIndexRoute
}

const CommunityRouteChildren: CommunityRouteChildren = {
  CommunityPostIdRoute: CommunityPostIdRoute,
  CommunityIndexRoute: CommunityIndexRoute,
}

const CommunityRouteWithChildren = CommunityRoute._addFileChildren(
  CommunityRouteChildren,
)

interface ProjectsRouteChildren {
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRoute
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsProjectIdRoute: ProjectsProjectIdRoute,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

interface ScriptsRouteChildren {
  ScriptsScriptIdRoute: typeof ScriptsScriptIdRoute
  ScriptsIndexRoute: typeof ScriptsIndexRoute
}

const ScriptsRouteChildren: ScriptsRouteChildren = {
  ScriptsScriptIdRoute: ScriptsScriptIdRoute,
  ScriptsIndexRoute: ScriptsIndexRoute,
}

const ScriptsRouteWithChildren =
  ScriptsRoute._addFileChildren(ScriptsRouteChildren)

interface ShowcaseRouteChildren {
  ShowcaseItemIdRoute: typeof ShowcaseItemIdRoute
}

const ShowcaseRouteChildren: ShowcaseRouteChildren = {
  ShowcaseItemIdRoute: ShowcaseItemIdRoute,
}

const ShowcaseRouteWithChildren = ShowcaseRoute._addFileChildren(
  ShowcaseRouteChildren,
)

interface TeamRouteChildren {
  TeamApprovalsRoute: typeof TeamApprovalsRoute
  TeamLogsRoute: typeof TeamLogsRoute
  TeamMembersRoute: typeof TeamMembersRoute
  TeamUsageRoute: typeof TeamUsageRoute
  TeamIndexRoute: typeof TeamIndexRoute
}

const TeamRouteChildren: TeamRouteChildren = {
  TeamApprovalsRoute: TeamApprovalsRoute,
  TeamLogsRoute: TeamLogsRoute,
  TeamMembersRoute: TeamMembersRoute,
  TeamUsageRoute: TeamUsageRoute,
  TeamIndexRoute: TeamIndexRoute,
}

const TeamRouteWithChildren = TeamRoute._addFileChildren(TeamRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  AssetsRoute: AssetsRoute,
  BasesRoute: BasesRoute,
  CharactersRoute: CharactersRouteWithChildren,
  CommunityRoute: CommunityRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HomeRoute: HomeRoute,
  LoginRoute: LoginRoute,
  ModelsRoute: ModelsRoute,
  PricingRoute: PricingRoute,
  ProjectsRoute: ProjectsRouteWithChildren,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ScriptsRoute: ScriptsRouteWithChildren,
  ShowcaseRoute: ShowcaseRouteWithChildren,
  TeamRoute: TeamRouteWithChildren,
  ZoclawRoute: ZoclawRoute,
  WorkspaceWorkspaceIdRoute: WorkspaceWorkspaceIdRoute,
  ApiPublicTestAitokenvibeRoute: ApiPublicTestAitokenvibeRoute,
  AssetsTabIdRoute: AssetsTabIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
