/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ZoclawRouteImport } from './routes/zoclaw'
import { Route as ShowcaseRouteImport } from './routes/showcase'
import { Route as ScriptsRouteImport } from './routes/scripts'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as ModelsRouteImport } from './routes/models'
import { Route as HomeRouteImport } from './routes/home'
import { Route as CharactersRouteImport } from './routes/characters'
import { Route as BasesRouteImport } from './routes/bases'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ScriptsNewRouteImport } from './routes/scripts.new'

const ZoclawRoute = ZoclawRouteImport.update({
  id: '/zoclaw',
  path: '/zoclaw',
  getParentRoute: () => rootRouteImport,
} as any)
const ShowcaseRoute = ShowcaseRouteImport.update({
  id: '/showcase',
  path: '/showcase',
  getParentRoute: () => rootRouteImport,
} as any)
const ScriptsRoute = ScriptsRouteImport.update({
  id: '/scripts',
  path: '/scripts',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelsRoute = ModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const CharactersRoute = CharactersRouteImport.update({
  id: '/characters',
  path: '/characters',
  getParentRoute: () => rootRouteImport,
} as any)
const BasesRoute = BasesRouteImport.update({
  id: '/bases',
  path: '/bases',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScriptsNewRoute = ScriptsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => ScriptsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bases': typeof BasesRoute
  '/characters': typeof CharactersRoute
  '/home': typeof HomeRoute
  '/models': typeof ModelsRoute
  '/pricing': typeof PricingRoute
  '/projects': typeof ProjectsRoute
  '/scripts': typeof ScriptsRouteWithChildren
  '/showcase': typeof ShowcaseRoute
  '/zoclaw': typeof ZoclawRoute
  '/scripts/new': typeof ScriptsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bases': typeof BasesRoute
  '/characters': typeof CharactersRoute
  '/home': typeof HomeRoute
  '/models': typeof ModelsRoute
  '/pricing': typeof PricingRoute
  '/projects': typeof ProjectsRoute
  '/scripts': typeof ScriptsRouteWithChildren
  '/showcase': typeof ShowcaseRoute
  '/zoclaw': typeof ZoclawRoute
  '/scripts/new': typeof ScriptsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bases': typeof BasesRoute
  '/characters': typeof CharactersRoute
  '/home': typeof HomeRoute
  '/models': typeof ModelsRoute
  '/pricing': typeof PricingRoute
  '/projects': typeof ProjectsRoute
  '/scripts': typeof ScriptsRouteWithChildren
  '/showcase': typeof ShowcaseRoute
  '/zoclaw': typeof ZoclawRoute
  '/scripts/new': typeof ScriptsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bases'
    | '/characters'
    | '/home'
    | '/models'
    | '/pricing'
    | '/projects'
    | '/scripts'
    | '/showcase'
    | '/zoclaw'
    | '/scripts/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bases'
    | '/characters'
    | '/home'
    | '/models'
    | '/pricing'
    | '/projects'
    | '/scripts'
    | '/showcase'
    | '/zoclaw'
    | '/scripts/new'
  id:
    | '__root__'
    | '/'
    | '/bases'
    | '/characters'
    | '/home'
    | '/models'
    | '/pricing'
    | '/projects'
    | '/scripts'
    | '/showcase'
    | '/zoclaw'
    | '/scripts/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BasesRoute: typeof BasesRoute
  CharactersRoute: typeof CharactersRoute
  HomeRoute: typeof HomeRoute
  ModelsRoute: typeof ModelsRoute
  PricingRoute: typeof PricingRoute
  ProjectsRoute: typeof ProjectsRoute
  ScriptsRoute: typeof ScriptsRouteWithChildren
  ShowcaseRoute: typeof ShowcaseRoute
  ZoclawRoute: typeof ZoclawRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/zoclaw': {
      id: '/zoclaw'
      path: '/zoclaw'
      fullPath: '/zoclaw'
      preLoaderRoute: typeof ZoclawRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/showcase': {
      id: '/showcase'
      path: '/showcase'
      fullPath: '/showcase'
      preLoaderRoute: typeof ShowcaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scripts': {
      id: '/scripts'
      path: '/scripts'
      fullPath: '/scripts'
      preLoaderRoute: typeof ScriptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/models': {
      id: '/models'
      path: '/models'
      fullPath: '/models'
      preLoaderRoute: typeof ModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/characters': {
      id: '/characters'
      path: '/characters'
      fullPath: '/characters'
      preLoaderRoute: typeof CharactersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bases': {
      id: '/bases'
      path: '/bases'
      fullPath: '/bases'
      preLoaderRoute: typeof BasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scripts/new': {
      id: '/scripts/new'
      path: '/new'
      fullPath: '/scripts/new'
      preLoaderRoute: typeof ScriptsNewRouteImport
      parentRoute: typeof ScriptsRoute
    }
  }
}

interface ScriptsRouteChildren {
  ScriptsNewRoute: typeof ScriptsNewRoute
}

const ScriptsRouteChildren: ScriptsRouteChildren = {
  ScriptsNewRoute: ScriptsNewRoute,
}

const ScriptsRouteWithChildren =
  ScriptsRoute._addFileChildren(ScriptsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BasesRoute: BasesRoute,
  CharactersRoute: CharactersRoute,
  HomeRoute: HomeRoute,
  ModelsRoute: ModelsRoute,
  PricingRoute: PricingRoute,
  ProjectsRoute: ProjectsRoute,
  ScriptsRoute: ScriptsRouteWithChildren,
  ShowcaseRoute: ShowcaseRoute,
  ZoclawRoute: ZoclawRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
